title: Raid Toolkit
email: raid.toolkit@gmail.com
description: "Raid Toolkit SDK Documentation Site"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://raid-toolkit.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs
logo: "/img/site-logo.png"
color_scheme: dark2

callouts_level: loud
callouts:
  tip:
    title: 💡Tip
    color: purple
  important:
    title: Important
    color: yellow
  info:
    title: Information
    color: purple
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: Raid Toolkit on GitHub
    url: https://github.com/raid-toolkit/raid-toolkit-sdk
  - title: Discord Community
    url: https://discord.gg/9vqjMs3wAC
